apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ .Release.Name }}-policy
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      io.kompose.service: {{ .Release.Name }}
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: web
      toPorts:
        - ports:
            - port: "6379"
              protocol: TCP
