apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    io.kompose.service: {{ .Release.Name }}
    {{ include "base.metadata.labels.managed_by" . | nindent 4 }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ include "base.metadata.annotations.release" . | nindent 4 }}
spec:
  serviceName: {{ .Release.Name | quote }}
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Release.Name }}
  template:
    metadata:
      labels:
        io.kompose.service: {{ .Release.Name }}
    spec:
      {{- if not .Values.singleNode }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
      {{- end }}
      containers:
        - name: {{ .Release.Name }}
          image: redis:7.2-alpine
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-secret
          env:
            - name: TZ
              value: Asia/Taipei
          args:
            - redis-server
            - --requirepass
            - "$(REDIS_PASSWORD)"
            - --maxmemory
            - 512mb
            - --maxmemory-policy
            - allkeys-lru
            - --appendonly
            - "yes"
          resources:
            requests:
              cpu: {{ .Values.service.resources.requests.cpu | default "50m" | quote }}
              memory: {{ .Values.service.resources.requests.memory | default "128Mi" | quote }}
            limits:
              cpu: {{ .Values.service.resources.limits.cpu | default "200m" | quote }}
              memory: {{ .Values.service.resources.limits.memory | default "512Mi" | quote }}
          volumeMounts:
            - mountPath: /data
              name: data
      restartPolicy: Always

  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.storageClass | default "local-path" }}
      resources:
        requests:
          storage: {{ .Values.data.resources.requests.storage | default "1Gi" }}
