apiVersion: v1
kind: Namespace
metadata:
  name: forgejo
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: forgejo
    meta.helm.sh/release-namespace: forgejo
    helm.sh/resource-policy: keep
