apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- web-namespace.yaml
- gateway-namespace.yaml
- internal-gateway-namespace.yaml
- service-namespace.yaml
- forgejo-namespace.yaml
- argocd-namespace.yaml
- monitor-namespace.yaml 
