forgejo-runner:
  knownLastVersion: true
  runner:
    config:
      create: true
      file:
        runner:
          capacity: 1
          envs: {}
          labels: []
        cache:
          enabled: false
