apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-backup-shell
  namespace: {{ .Release.Namespace | quote }}
data:
  database-backup.sh: |
    #!/bin/sh

    RECENT_COUNT=$(find /backups -name "forgejo_*.sql.gz" -mmin -7200 | wc -l)
    TODAY_FILE="/backups/forgejo_$(date +%Y%m%d).sql.gz"
    if [ "$RECENT_COUNT" -ge 5 ]; then
    :
    elif [ -f "$TODAY_FILE" ]; then
    :
    else
      PGPASSWORD="${DB_BACKUP_PASSWORD}" pg_dump \
        -h forgejo-database \
        -U "${DB_BACKUP_USERNAME}" \
        -d "${DB_DATABASE}" \
        --no-owner \
        --no-privileges \
        | gzip > "$TODAY_FILE"

      find /backups -name "forgejo_*.sql.gz" -mtime +30 -delete
    fi
