apiVersion: v1
kind: ConfigMap
metadata:
  name: road-runner-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{ include "base.metadata.labels.managed_by" . | nindent 4 }}
  annotations:
    {{ include "base.metadata.annotations.release" . | nindent 4 }}
data:
  .rr.yaml: |
    version: '3'
    rpc:
      listen: 'tcp://127.0.0.1:6001'
    server:
      command: 'php vendor/bin/rr-worker start'
    
    temporal:
      address: "${TEMPORAL_FRONTEND_ADDRESS}"
      activities:
        num_workers: 3
    metrics:
      address: "0.0.0.0:2112"
    status:
      address: 0.0.0.0:2114

