apiVersion: v1
kind: PersistentVolumeClaim # pv 已經建立好僅僅只是claim 他的pod
metadata:
  name: database-backup-claim
  namespace: {{ .Release.Namespace | quote }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.database_backup.resources.requests.storage | default "1Gi" | quote}}
    limits:
      storage: {{ .Values.database_backup.resources.limits.storage | default "1Gi" | quote}}
  volumeName: nas-backup-pv
  # 找到 deploy/helm/base/charts/storage/templates/database-backup-storage.yaml
  storageClassName: "nas-backup-storage"
