apiVersion: v1
kind: Service
metadata:
  name: forgejo-gateway-proxy
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{ include "common.gateway.metadata.labels.managed_by" . | nindent 4 }}
  annotations:
    {{ include "common.gateway.metadata.annotations.release" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: forgejo-http.forgejo.svc.cluster.local.
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
