apiVersion: v1
kind: Service
metadata:
  name: grafana-gateway-proxy
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{ include "common.gateway.metadata.labels.managed_by" . | nindent 4 }}
  annotations:
    {{ include "common.gateway.metadata.annotations.release" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: kube-prometheus-stack-grafana.monitoring.svc.cluster.local.
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
