apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: internal-body-size
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{ include "common.gateway.metadata.labels.managed_by" . | nindent 4 }}
spec:
  buffering:
    maxRequestBodyBytes: 57671680  # 55m
