apiVersion: v1
kind: Service
metadata:
  name: external-gateway-proxy  # 名稱跟你在 Ingress 裡寫的一樣
  namespace:  {{ .Release.Namespace | quote }}       # 必須放在跟 Ingress 同一個地方
  labels:
    {{ include "common.gateway.metadata.labels.managed_by" . | nindent 4 }}
  annotations:
    {{ include "common.gateway.metadata.annotations.release" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: internal-gateway-service.internal-gateway.svc.cluster.local.
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
