apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: traefik-external-egress
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: traefik
  egress:
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: traefik
            io.kubernetes.pod.namespace: internal-gateway
      toPorts:
        - ports:
            - port: "8000"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            io.kompose.service: local-registry
            io.kubernetes.pod.namespace: default
      toPorts:
        - ports:
            - port: "5000"
              protocol: TCP
