apiVersion: v1
kind: Service
metadata:
  name: registry-gateway-proxy
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{ include "common.gateway.metadata.labels.managed_by" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: my-local-registry.default.svc.cluster.local.
  ports:
    - port: 5000
