singleNode: true

sql:
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

database:
  storage: 10Gi

database_backup:
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
      storage: "1Gi"
    limits:
      cpu: "500m"
      memory: "512Mi"
      storage: "10Gi"
