apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: web-redis-network
  namespace: web
  labels:
    {{ include "base.metadata.labels.managed_by" . | nindent 4 }}
  annotations:
    {{ include "base.metadata.annotations.release" . | nindent 4 }}
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/web-redis-network: "true"
        - podSelector:
            matchLabels:
              io.kompose.network/web-app-network: "true"   # 💥 重點：允許 Laravel 連進來
  podSelector:
    matchLabels:
      io.kompose.network/web-redis-network: "true"
