apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: forgejo-database
    {{ include "base.metadata.labels.managed_by" . | nindent 4 }}
  name: forgejo-database
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{ include "base.metadata.annotations.release" . | nindent 4 }}
spec:
  ports:
    - name: "database-port"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: forgejo-database
